# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180818_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artile',
            new_name='article',
        ),
    ]
